### ISSUE TITLE
Indentation broken in vim with line numbers

### ISSUE THREAD

**Issue by mtslzr** [danieldelcore/hyper-match#2]
Running Hyper 1.4.8 on macOS High Sierra. With the plugin enabled, turning on "set number" in vim (to show line numbers) breaks indentation/spacing. This seems to be the same/similar to https://github.com/zeit/hyperlinks/issues/4.

Here's it broken:
<img width="454" alt="screen shot 2017-10-26 at 12 09 45" src="https://user-images.githubusercontent.com/6003715/32066899-ec3096bc-ba46-11e7-9989-658647f7c58f.png">

And here is after turning off line numbers:
<img width="432" alt="screen shot 2017-10-26 at 12 09 57" src="https://user-images.githubusercontent.com/6003715/32066910-f5cfb252-ba46-11e7-8f62-b9696e63cae0.png">

**Comment by delcore92** [comment]
Oh! Thanks for letting me know. I'll have a look into it asap!

**Comment by mtslzr** [comment]
This appears to have been resolved by Hyper 2.0.0 Working now on macOS Mojave (10.41.1) running Hyper 2.0.0.
